/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_arvin_bspatch_BSPatch */

#ifndef _Included_com_arvin_bspatch_BSPatch
#define _Included_com_arvin_bspatch_BSPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arvin_bspatch_BSPatch
 * Method:    mergeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_arvin_bspatch_BSPatch_mergeFile
        (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif

#define TAG "BSPatch"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG,TAG,__VA_ARGS__)
